{{- if include "valkey.renderAuthSecret" . | eq "true" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "valkey.fullname" . }}-auth
  labels:
    {{- include "valkey.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "valkey.authSecretData" . | nindent 2 }}
{{- end }}
